# Generated by Django 6.0.1 on 2026-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
