# Generated by Django 6.0.1 on 2026-01-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: DeepSeek V3, GPT-4o', max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('claude', 'Claude (Anthropic)'), ('custom', 'Custom (OpenAI Compatible)')], default='deepseek', max_length=20, verbose_name='服务商')),
                ('api_key', models.CharField(help_text='以 sk- 开头的密钥', max_length=255, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, help_text='可选，例如: https://api.deepseek.com', null=True, verbose_name='Base URL')),
                ('model_name', models.CharField(help_text='API调用的模型ID，例如: deepseek-chat', max_length=100, verbose_name='模型ID')),
                ('is_active', models.BooleanField(default=False, help_text='系统中只能有一个活跃的默认模型', verbose_name='设为默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: Weather, Brave Search', max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, help_text='这个 MCP 服务的用途说明', verbose_name='描述')),
                ('server_type', models.CharField(choices=[('stdio', 'STDIO (本地进程)'), ('sse', 'SSE (远程服务)')], default='stdio', max_length=10, verbose_name='连接方式')),
                ('command', models.CharField(blank=True, help_text='STDIO 模式的启动命令，例如: npx -y @anthropic/mcp-server-fetch', max_length=500, verbose_name='启动命令')),
                ('args', models.JSONField(blank=True, default=list, help_text='命令行参数列表，例如: ["--port", "3000"]', verbose_name='命令参数')),
                ('endpoint_url', models.URLField(blank=True, help_text='SSE 模式的服务端点 URL', null=True, verbose_name='SSE Endpoint')),
                ('env_vars', models.JSONField(blank=True, default=dict, help_text='传递给 MCP Server 的环境变量，例如: {"API_KEY": "xxx"}', verbose_name='环境变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('status', models.CharField(choices=[('unknown', '未检测'), ('connected', '已连接'), ('failed', '连接失败')], default='unknown', max_length=20, verbose_name='连接状态')),
                ('available_tools', models.JSONField(blank=True, default=list, help_text='检测成功后自动填充的工具列表', verbose_name='可用工具')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='上次检测时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP 服务配置',
                'verbose_name_plural': 'MCP 服务配置',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
