# Generated by Django 6.0.1 on 2026-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_key',
            field=models.CharField(help_text='从服务商控制台获取的密钥', max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='通常无需修改，选择服务商后自动填充', verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='系统中只能有一个默认模型', verbose_name='设为默认'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(blank=True, help_text='选择服务商后会显示可用模型', max_length=100, verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='name',
            field=models.CharField(help_text='便于识别，例如: 公司DeepSeek账号', max_length=100, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek (深度求索)'), ('qwen', '通义千问 (阿里云)'), ('openai', 'OpenAI'), ('claude', 'Claude (Anthropic)'), ('custom', '自定义 (OpenAI 兼容)')], default='deepseek', max_length=20, verbose_name='服务商'),
        ),
    ]
