# Generated by Django 6.0.1 on 2026-01-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_llmconfig_updated_at_alter_llmconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='available_models',
            field=models.JSONField(blank=True, default=list, help_text='从 API 动态获取的模型列表', verbose_name='可用模型列表'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间'),
        ),
    ]
