# Generated by Django 6.0.1 on 2026-01-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_llmconfig_available_models_llmconfig_last_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='server_type',
            field=models.CharField(choices=[('stdio', 'STDIO (本地进程)'), ('http', 'Streamable HTTP (远程服务)')], default='stdio', max_length=10, verbose_name='连接方式'),
        ),
    ]
