# Generated by Django 6.0.1 on 2026-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='documents/', verbose_name='文件')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('indexed', '已索引'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
