# Generated by Django 6.0.1 on 2026-01-16 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='支持格式: PDF, DOCX, PPTX, XLSX, CSV, TXT, MD, HTML, XML, EPUB', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'xlsx', 'csv', 'txt', 'md', 'html', 'xml', 'epub'])], verbose_name='文件'),
        ),
    ]
